def muz(l,a=2,b=0.5):
    import winsound
    def s(t):
            j=0
            while(j<len(t)):
                if(t[j]=="1"):
                    winsound.Beep(a*240,int(b*800))
                elif(t[j]=="2"):
                    winsound.Beep(a*270,int(b*800))
                elif(t[j]=="3"):
                    winsound.Beep(a*300,int(b*800))
                elif(t[j]=="4"):
                    winsound.Beep(a*320,int(b*800))
                elif(t[j]=="5"):
                    winsound.Beep(a*360,int(b*800))
                elif(t[j]=="6"):
                    winsound.Beep(a*400,int(b*800))
                elif(t[j]=="7"):
                    winsound.Beep(a*450,int(b*800))
                elif(t[j]=="/"):
                    if(j!=len(t)-1):
                        if(t[j+1]=="2"):
                            winsound.Beep(a*256,int(b*800))
                        elif(t[j+1]=="3"):
                            winsound.Beep(a*288,int(b*800))    
                            
                        elif(t[j+1]=="4"):
                            winsound.Beep(a*337,int(b*800))
                            
                        elif(t[j+1]=="6"):
                            winsound.Beep(a*384,int(b*800))
                            
                        elif(t[j+1]=="7"):
                            winsound.Beep(a*432,int(b*800))
                        elif(t[j+1]=="*"):
                            if(t[j+2]=="2"):
                                winsound.Beep(a*128,int(b*800))
                            elif(t[j+2]=="3"):
                                winsound.Beep(a*144,int(b*800))    
                                
                            elif(t[j+2]=="4"):
                                winsound.Beep(a*168,int(b*800))
                                
                            elif(t[j+2]=="6"):
                                winsound.Beep(a*192,int(b*800))
                                
                            elif(t[j+2]=="7"):
                                winsound.Beep(a*216,int(b*800))
                            j+=1
                        elif(t[j+1]=="-"):
                            if(t[j+2]=="2"):
                                winsound.Beep(a*512,int(b*800))
                            elif(t[j+2]=="3"):
                                winsound.Beep(a*144*4,int(b*800))    
                                
                            elif(t[j+2]=="4"):
                                winsound.Beep(a*168*4,int(b*800))
                                
                            elif(t[j+2]=="6"):
                                winsound.Beep(a*192*4,int(b*800))
                                
                            elif(t[j+2]=="7"):
                                winsound.Beep(a*216*4,int(b*800))
                            j+=1
                        j+=1
                elif(t[j]=="*"):
                    if(t[j+1]=="1"):
                        winsound.Beep(a*120,int(b*800))
                    elif(t[j]=="2"):
                        winsound.Beep(a*135,int(b*800))
                    elif(t[j]=="3"):
                        winsound.Beep(a*150,int(b*800))
                    elif(t[j]=="4"):
                        winsound.Beep(a*160,int(b*800))
                    elif(t[j]=="5"):
                        winsound.Beep(a*180,int(b*800))
                    elif(t[j]=="6"):
                        winsound.Beep(a*200,int(b*800))
                    elif(t[j]=="7"):
                        winsound.Beep(a*225,int(b*800))
                    j+=1
                elif(t[j]=="-"):
                    if(t[j+1]=="1"):
                        winsound.Beep(a*120*4,int(b*800))
                    elif(t[j]=="2"):
                        winsound.Beep(a*135*4,int(b*800))
                    elif(t[j]=="3"):
                        winsound.Beep(a*150*4,int(b*800))
                    elif(t[j]=="4"):
                        winsound.Beep(a*160*4,int(b*800))
                    elif(t[j]=="5"):
                        winsound.Beep(a*180*4,int(b*800))
                    elif(t[j]=="6"):
                        winsound.Beep(a*200*4,int(b*800))
                    elif(t[j]=="7"):
                        winsound.Beep(a*225*4,int(b*800))
                    j+=1
                    
                    
                
                j+=1
    i=0
    while(i<len(l)):
        if(l[i]=="1"):
            winsound.Beep(a*240,int(b*800))
            k="1"
        elif(l[i]=="2"):
            winsound.Beep(a*270,int(b*800))
            k="2"
        elif(l[i]=="3"):
            winsound.Beep(a*300,int(b*800))
            k="3"
        elif(l[i]=="4"):
            winsound.Beep(a*320,int(b*800))
            k="4"
        elif(l[i]=="5"):
            winsound.Beep(a*360,int(b*800))
            k="5"
        elif(l[i]=="6"):
            winsound.Beep(a*400,int(b*800))
            k="6"
        elif(l[i]=="7"):
            winsound.Beep(a*450,int(b*800))
            k="7"
        elif(l[i]=="/"):
            if(i!=len(l)-1):
                if(l[i+1]=="2"):
                    winsound.Beep(a*256,int(b*800))
                    k="/2"
                elif(l[i+1]=="3"):
                    winsound.Beep(a*288,int(b*800))    
                    k="/3"
                elif(l[i+1]=="4"):
                    winsound.Beep(a*337,int(b*800))
                    k="/4"
                elif(l[i+1]=="6"):
                    winsound.Beep(a*384,int(b*800))
                    k="/6"
                elif(l[i+1]=="7"):
                    winsound.Beep(a*432,int(b*800))
                    k="/7"
                elif(l[i+1]=="*"):
                    if(l[i+2]=="2"):
                        winsound.Beep(a*128,int(b*800))
                        k="/*2"
                    elif(l[i+2]=="3"):
                        winsound.Beep(a*144,int(b*800))    
                        k="/*3"
                    elif(l[i+2]=="4"):
                        winsound.Beep(a*168,int(b*800))
                        k="/*4"
                    elif(l[i+2]=="6"):
                        winsound.Beep(a*192,int(b*800))
                        k="/*6"
                    elif(l[i+2]=="7"):
                        winsound.Beep(a*216,int(b*800))
                        k="/*7"
                    i+=1
                elif(l[i+1]=="-"):
                    if(l[i+2]=="2"):
                        winsound.Beep(a*512,int(b*800))
                        k="/-2"
                    elif(l[i+2]=="3"):
                        winsound.Beep(a*144*4,int(b*800))    
                        k="/-3"
                    elif(l[i+2]=="4"):
                        winsound.Beep(a*168*4,int(b*800))
                        k="/-4"
                    elif(l[i+2]=="6"):
                        winsound.Beep(a*192*4,int(b*800))
                        k="/-6"
                    elif(l[i+2]=="7"):
                        winsound.Beep(a*216*4,int(b*800))
                        k="/-7"
                    i+=1
                i+=1
        elif(l[i]=="*"):
            if(l[i+1]=="1"):
                winsound.Beep(a*120,int(b*800))
                k="*1"
            elif(l[i]=="2"):
                winsound.Beep(a*135,int(b*800))
                k="*1"
            elif(l[i]=="3"):
                winsound.Beep(a*150,int(b*800))
                k="*1"
            elif(l[i]=="4"):
                winsound.Beep(a*160,int(b*800))
                k="*1"
            elif(l[i]=="5"):
                winsound.Beep(a*180,int(b*800))
                k="*1"
            elif(l[i]=="6"):
                winsound.Beep(a*200,int(b*800))
                k="*1"
            elif(l[i]=="7"):
                winsound.Beep(a*225,int(b*800))
                k="*1"
            i+=1
        elif(l[i]=="-"):
            if(l[i+1]=="1"):
                winsound.Beep(a*120*4,int(b*800))
                k="-1"
            elif(l[i]=="2"):
                winsound.Beep(a*135*4,int(b*800))
                k="-1"
            elif(l[i]=="3"):
                winsound.Beep(a*150*4,int(b*800))
                k="-1"
            elif(l[i]=="4"):
                winsound.Beep(a*160*4,int(b*800))
                k="-1"
            elif(l[i]=="5"):
                winsound.Beep(a*180*4,int(b*800))
                k="-1"
            elif(l[i]=="6"):
                winsound.Beep(a*200*4,int(b*800))
                k="-1"
            elif(l[i]=="7"):
                winsound.Beep(a*225*4,int(b*800))
            i+=1
        elif(l[i]==" "):
            s(k)
        i+=1

        
while(1>0):
    import random
    a=["1","2","3","4","5","6","7","*","-",]
    z=["1","2","3","4","5","6","7"]
    x=""
    for i in range(8):
        b=random.randrange(0,9)
        c=a[b]
        x=x+c
    if(c=="*" or c=="-"):
        w=random.randrange(0,7)
        y=z[w]
        x=x+y
    print(x)
    muz(x,2,0.5)        
